collection: rating_criteria_values
field: verified_by
related_collection: directus_users
meta:
  junction_field: null
  many_collection: rating_criteria_values
  many_field: verified_by
  one_allowed_collections: null
  one_collection: directus_users
  one_collection_field: null
  one_deselect_action: nullify
  one_field: null
  sort_field: null
schema:
  table: rating_criteria_values
  column: verified_by
  foreign_key_table: directus_users
  foreign_key_column: id
  constraint_name: rating_criteria_values_verified_by_foreign
  on_update: NO ACTION
  on_delete: SET NULL
