collection: rating_criteria_values
field: rating_measure_id
related_collection: ratings_measures
meta:
  junction_field: null
  many_collection: rating_criteria_values
  many_field: rating_measure_id
  one_allowed_collections: null
  one_collection: ratings_measures
  one_collection_field: null
  one_deselect_action: nullify
  one_field: criteria_values
  sort_field: null
schema:
  table: rating_criteria_values
  column: rating_measure_id
  foreign_key_table: ratings_measures
  foreign_key_column: id
  constraint_name: rating_criteria_values_rating_measure_id_foreign
  on_update: NO ACTION
  on_delete: CASCADE
