collection: rating_criteria_values
field: criterion_definition_id
related_collection: rating_criteria_definitions
meta:
  junction_field: null
  many_collection: rating_criteria_values
  many_field: criterion_definition_id
  one_allowed_collections: null
  one_collection: rating_criteria_definitions
  one_collection_field: null
  one_deselect_action: nullify
  one_field: values
  sort_field: null
schema:
  table: rating_criteria_values
  column: criterion_definition_id
  foreign_key_table: rating_criteria_definitions
  foreign_key_column: id
  constraint_name: rating_criteria_values_criterion_definition_id_foreign
  on_update: NO ACTION
  on_delete: CASCADE
