collection: rating_criteria_sources
field: criteria_value_id
related_collection: rating_criteria_values
meta:
  junction_field: source_id
  many_collection: rating_criteria_sources
  many_field: criteria_value_id
  one_allowed_collections: null
  one_collection: rating_criteria_values
  one_collection_field: null
  one_deselect_action: nullify
  one_field: sources
  sort_field: null
schema:
  table: rating_criteria_sources
  column: criteria_value_id
  foreign_key_table: rating_criteria_values
  foreign_key_column: id
  constraint_name: rating_criteria_sources_criteria_value_id_foreign
  on_update: NO ACTION
  on_delete: CASCADE
