collection: rating_criteria_values
field: id
type: uuid
meta:
  collection: rating_criteria_values
  conditions: null
  display: null
  display_options: null
  field: id
  group: null
  hidden: true
  interface: input
  note: null
  options: null
  readonly: true
  required: false
  sort: 1
  special:
    - uuid
  translations: null
  validation: null
  validation_message: null
  width: full
schema:
  name: id
  table: rating_criteria_values
  data_type: uuid
  default_value: null
  max_length: null
  numeric_precision: null
  numeric_scale: null
  is_nullable: false
  is_unique: true
  is_primary_key: true
  has_auto_increment: false
  is_generated: false
  generation_expression: null
  foreign_key_table: null
  foreign_key_column: null
