id: 3a964766-0e61-4140-90ff-38654594cda2
name: EditorMeasures
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: true
permissions:
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: measures
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - sort
      - user_created
      - date_created
      - user_updated
      - date_updated
      - name
      - sector
      - impact
      - weight
      - feasibility
      - feasibility_political
      - feasibility_economical
      - description
      - verification_description
      - notes
      - id
      - choices_rating
      - accordion-p4jgb8
      - description_evaluation_criteria
      - description_about
      - description_benefit
      - description_contribution
      - description_verification
      - description_implementation
      - description_legal
      - description_funding
      - description_tutorial
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: measures
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - id
      - sort
      - user_created
      - date_created
      - user_updated
      - date_updated
      - name
      - sector
      - impact
      - weight
      - feasibility
      - feasibility_political
      - feasibility_economical
      - description
      - verification_description
      - notes
      - choices_rating
      - accordion-p4jgb8
      - description_evaluation_criteria
      - description_about
      - description_benefit
      - description_verification
      - description_contribution
      - description_implementation
      - description_legal
      - description_funding
      - description_tutorial
