name: Ma√ünahmenteam
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: true
permissions:
  - collection: directus_dashboards
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: directus_users
    action: read
    permissions:
      _and:
        - id:
            _eq: $CURRENT_USER
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: directus_users
    action: update
    permissions:
      _and:
        - id:
            _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - password
  - collection: localteams
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - id
      - name
      - municipality_name
      - municipality_id
      - slug
      - date_updated
      - date_created
      - status
  - collection: editors
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - id
      - email
      - internal_comment
      - localteam_id
      - organisation
      - date_created
      - date_updated
  - collection: measure_catalog
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measure_catalog
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measure_catalog
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measure_catalog
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: municipalities
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - status
      - id
      - date_created
      - date_updated
      - overall_status_comment
      - name
      - slug
      - municipality_type
      - localteam_id
      - details
      - description
      - state
      - population
      - mayor
      - party_mayor
      - geolocation
      - scores
      - percentage_rated
      - notice-kcc40f
      - public_contact
      - links-g1sxxi
  - collection: municipality_scores
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: ratings_measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - id
      - status
      - measure_published
      - date_created
      - date_updated
      - measure_id
      - links-jv6and
      - internal_note
      - applicable
      - localteam_id
      - why_not_applicable
      - choices
      - rating
      - current_progress
      - source
      - approved
